#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════
# BLAXIN — Version bump helper
#
# Single source of truth: blaxin/VERSION
#   $ bash scripts/bump-version.sh 1.1.2
#
# Updates every in-repo version constant so UI, backend, package and
# build all report the same version. The git tag (vX.Y.Z) is the release
# source of truth; this keeps the repo in sync with it before tagging.
# ═══════════════════════════════════════════════════════════════════════
set -euo pipefail

NEW_VERSION="${1:-}"
if [[ -z "${NEW_VERSION}" ]]; then
    echo "Usage: bash scripts/bump-version.sh <x.y.z>" >&2
    exit 2
fi
if ! [[ "${NEW_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "ERROR: version must look like x.y.z (got: ${NEW_VERSION})" >&2
    exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

echo "Bumping BLAXIN version → ${NEW_VERSION}"

# Source of truth
echo "${NEW_VERSION}" > blaxin/VERSION

# Server + client package.json (and their lockfiles)
(cd blaxin/server && npm version "${NEW_VERSION}" --no-git-tag-version --allow-same-version >/dev/null)
(cd blaxin/client && npm version "${NEW_VERSION}" --no-git-tag-version --allow-same-version >/dev/null)

# Tauri config + Cargo
sed -i "s/\"version\": \".*\"/\"version\": \"${NEW_VERSION}\"/" blaxin/src-tauri/tauri.conf.json
sed -i "s/^version = \".*\"/version = \"${NEW_VERSION}\"/" blaxin/src-tauri/Cargo.toml

# Server version constant (served by /api/health and /api/version)
sed -i "s/export const APP_VERSION = '.*'/export const APP_VERSION = '${NEW_VERSION}'/" blaxin/server/src/utils/version.ts

# Client sidebar label (branded footer)
sed -i "s|BLAXIN v[0-9.]*|BLAXIN v${NEW_VERSION}|" blaxin/client/src/components/Sidebar.tsx

# Bundled-server copy used by local Tauri builds (regenerated by CI)
if [[ -f blaxin/resources/blaxin-server/package.json ]]; then
    sed -i "s/\"version\": \".*\"/\"version\": \"${NEW_VERSION}\"/" blaxin/resources/blaxin-server/package.json
fi

echo ""
echo "✓ All version constants updated to ${NEW_VERSION}"
grep -h "version" blaxin/VERSION
echo ""
echo "Review and commit, then tag:"
echo "  git add -A && git commit -m \"release: v${NEW_VERSION}\""
echo "  git push origin main"
echo "  git tag v${NEW_VERSION} && git push origin v${NEW_VERSION}"
